import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

export const generateIdeaKitPDF = async (ideaData, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50
      });

      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Header
      doc.fontSize(28).font('Helvetica-Bold').text('Token Ideation Kit', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica').fillColor('#666').text('Generated by Token Ideator Platform', { align: 'center' });
      doc.moveDown(1);

      // Project Details Section
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Project Details');
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#ddd');
      doc.moveDown(0.5);

      doc.fontSize(11).font('Helvetica-Bold').text('Project Idea:');
      doc.fontSize(10).font('Helvetica').fillColor('#333').text(ideaData.projectIdea, { width: 450 });
      doc.moveDown(0.5);

      if (ideaData.founderName) {
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#000').text('Founder/VC:');
        doc.fontSize(10).font('Helvetica').fillColor('#333').text(ideaData.founderName);
        doc.moveDown(0.5);
      }

      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000').text('Generation Date:');
      doc.fontSize(10).font('Helvetica').fillColor('#333').text(new Date().toLocaleDateString());
      doc.moveDown(1);

      // Token Branding Section
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Token Branding');
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#ddd');
      doc.moveDown(0.5);

      // Token Name and Symbol
      doc.fontSize(24).font('Helvetica-Bold').fillColor('#1a73e8').text(ideaData.tokenData.tokenName);
      doc.fontSize(14).font('Helvetica').fillColor('#666').text(`Symbol: ${ideaData.tokenData.symbol}`);
      doc.moveDown(0.5);

      // Tagline
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Tagline:');
      doc.fontSize(11).font('Helvetica').fillColor('#333').text(ideaData.tokenData.tagline);
      doc.moveDown(0.5);

      // Visual Style
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Visual Style:');
      doc.fontSize(10).font('Helvetica').fillColor('#333').text(ideaData.tokenData.visualStyle, { width: 450 });
      doc.moveDown(0.5);

      // Color Palette
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Color Palette:');
      doc.moveDown(0.3);
      ideaData.tokenData.colors.forEach((color, index) => {
        doc.rect(60, doc.y, 20, 20).fill(color);
        doc.fontSize(10).fillColor('#333').text(`${color}`, 90, doc.y);
        doc.moveDown(0.3);
      });
      doc.moveDown(0.5);

      // Project Description
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Project Description');
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#ddd');
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').fillColor('#333').text(ideaData.projectDescription, { width: 450, align: 'justify' });
      doc.moveDown(1);

      // Logo Prompt
      if (ideaData.logoPrompt) {
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Logo Design Prompt');
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#ddd');
        doc.moveDown(0.5);
        doc.fontSize(9).font('Helvetica').fillColor('#555').text(ideaData.logoPrompt, { width: 450 });
        doc.moveDown(1);
      }

      // Footer
      doc.fontSize(9).fillColor('#999').text('This document is confidential and for internal use only.', { align: 'center' });
      doc.text(`Generated on ${new Date().toISOString()}`, { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve(outputPath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (error) {
      reject(error);
    }
  });
};
